package uqpay

const (
	INTERVAL_PER_TRANSACTION = "PER_TRANSACTION" // 频率周期，每笔交易
	DEFAULT_CONTROLS_AMOUNT  = "20000.00"
)

// 持卡人三方状态枚举
const (
	THIRD_PARTY_UP_CARD_HOLDER_STATUS_ENUM_PENDING       = "PENDING"    // 审核中
	THIRD_PARTY_UP_CARD_HOLDER_STATUS_ENUM_SUCCESS       = "SUCCESS"    // 成功
	THIRD_PARTY_UP_CARD_HOLDER_STATUS_ENUM_FAILED        = "FAILED"     // 失败
	THIRD_PARTY_UP_CARD_HOLDER_STATUS_ENUM_UP_INCOMPLETE = "INCOMPLETE" // 不完整
)

// 三方卡状态枚举: PENDING,ACTIVE, FROZEN, BLOCKED, PRE_CANCEL,CANCELLED,LOST,STOLEN,FAILED
const (
	THIRD_PARTY_UP_CARD_STATUS_ENUM_PENDING    = "PENDING"    // 审核中
	THIRD_PARTY_UP_CARD_STATUS_ENUM_ACTIVE     = "ACTIVE"     // ACTIVE
	THIRD_PARTY_UP_CARD_STATUS_ENUM_FROZEN     = "FROZEN"     // 冻结
	THIRD_PARTY_UP_CARD_STATUS_ENUM_BLOCKED    = "BLOCKED"    // 已屏蔽
	THIRD_PARTY_UP_CARD_STATUS_ENUM_PRE_CANCEL = "PRE_CANCEL" // 注销前
	THIRD_PARTY_UP_CARD_STATUS_ENUM_CANCELLED  = "CANCELLED"  // 注销
	THIRD_PARTY_UP_CARD_STATUS_ENUM_LOST       = "LOST"       // 丢失
	THIRD_PARTY_UP_CARD_STATUS_ENUM_STOLEN     = "STOLEN"     // 被盗
	THIRD_PARTY_UP_CARD_STATUS_ENUM_FAILED     = "FAILED"     // 失败
)

const (
	THIRD_PARTY_UP_ORDER_STATUS_ENUM_PENDING    = "PENDING"    // The initial status of the order request.
	THIRD_PARTY_UP_ORDER_STATUS_ENUM_PROCESSING = "PROCESSING" // If this status shall be subject to webhooks notification.
	THIRD_PARTY_UP_ORDER_STATUS_ENUM_SUCCESS    = "SUCCESS"    // The final status of the order request is successful.
	THIRD_PARTY_UP_ORDER_STATUS_ENUM_FAILED     = "FAILED"     // The final status of the order request is failed.
)

const (
	THIRD_PARTY_UP_CARD_MODE_ENUM_SINGLE = "SINGLE"
	THIRD_PARTY_UP_CARD_MODE_ENUM_SHARE  = "SHARE" // 卡片模式
)
